# Project information
site_name: PHOTONAI Projects
repo_name: 'photonai_projects'
repo_url: 'https://github.com/wwu-mmll/photonai_projects'
site_url: 'https://wwu-mmll.github.io/photonai_projects/'
docs_dir: 'documentation/docs'
#site_dir: 'site'
edit_uri: 'edit/master/documentation/docs'

# Theme configuration
theme:
  name: 'material'
  language: en
  palette:
    primary: custom
    accent: custom
  font:
    text: Figtree
  logo: assets/img/CCCPM.png
  favicon: assets/img/CCCPM.png
  features:
     - toc.follow
     - navigation.tabs
     - navigation.sections

# extensions
markdown_extensions:
  - pymdownx.arithmatex:
        generic: true
  - pymdownx.highlight:
      auto_title: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: "../"
  - pymdownx.superfences
  - codehilite
  - admonition
  - pymdownx.details

# Site structure
nav:
- Home: 'index.md'
- Installation: 'installation.md'
- Getting Started: 'getting_started.md'
- Examples:
    - Simulated Data: 'examples/simulated_data.md'
    - HCP: 'examples/human_connectome_project.md'
- API:
    - CPM Regression: api/cpm_regression.md
    - Edge Selection: api/edge_selection.md
    - Models: api/models.md
    - Fold: api/fold.md
    - Results Manager: api/results_manager.md

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: False
          paths:
            [.]